### ISSUE TITLE
Installation Exception: Extensions not supported: ['all']. Supported extensions: []

### ISSUE THREAD

**Issue by ryan-z** [second-state/WasmEdge-tensorflow-tools#6]
Hello, I'm trying to install the wasmedge-tensorflow-lite tool on an Apple M1. I previously installed WasmEdge without extensions, but I'm now trying to add them. I tried the install steps from the [official book](https://wasmedge.org/book/en/quick_start/install.html#quick-install) which showed the same exception.

```
$ wget -qO- https://raw.githubusercontent.com/WasmEdge/WasmEdge/master/utils/install.sh | bash -s -- -e all -v 0.12.0-alpha.1
Using Python: /opt/homebrew/bin/python3
Traceback (most recent call last):
  File "<stdin>", line 1667, in <module>
  File "<stdin>", line 1412, in main
  File "<stdin>", line 1353, in __bool__
  File "<stdin>", line 1365, in bool_overload
  File "<stdin>", line 56, in reraise
Exception: Extensions not supported: ['all']. Supported extensions: []
```

**Comment by ryan-z** [comment]
Never mind, closing this because apparently only x86 binaries are supported by Tensorflow:
https://www.tensorflow.org/install/lang_c#download_and_extract
